# Generated by Django 4.2 on 2026-03-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogInteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('message_text', models.TextField()),
                ('ai_response', models.TextField()),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('latency', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Logs Técnicos',
                'db_table': 'logs_interacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResumoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, verbose_name='ID da Sessão')),
                ('total_mensagens', models.IntegerField(verbose_name='Qtd Mensagens')),
                ('ultima_interacao', models.DateTimeField(verbose_name='Última Atividade')),
                ('ip_cliente', models.GenericIPAddressField(verbose_name='IP do Usuário')),
                ('latencia_media', models.FloatField(verbose_name='Latência Média (s)')),
            ],
            options={
                'verbose_name': 'Relatório de Chat',
                'verbose_name_plural': 'Relatórios de Chats',
                'db_table': 'vw_resumo_sessoes',
                'managed': False,
            },
        ),
    ]
